### ISSUE TITLE
Optimize `btreemap::range(...).count()`

### ISSUE THREAD

**Issue by peterpeterparker** [dfinity/stable-structures#189]
## Features

It would be nice to expose a more performant way to get to know the number of entries in the stable structure btreemap where keys belong to the specified range than `my_btree_map.range().count()`.

## Context

In Juno, while I still need to perform quite some work to improve my code's usage of stable structures, I have exposed a few "count documents and assets" functions. These functions inform the developer about the number of elements in a collection. Therefore, it would be handy for my use case if such information could be found in a performant way.

## Notes

- Follow-up of [forum thread](https://forum.dfinity.org/t/stable-structure-range-length/27223/2?u=peterparker).

- This suggestion is not a blocker on my side.

**Comment by ielashi** [comment]
@peterpeterparker with #190, `range(...)count()` should be much faster. Here are our benchmarks:

```
---------------------------------------------------

Benchmark: btreemap_iter_count_small_values
  total:
    instructions: 10.12 M (improved by 60.45%)
    heap_increase: 0 pages (no change)
    stable_memory_increase: 0 pages (no change)

---------------------------------------------------

Benchmark: btreemap_iter_count_10mib_values
  total:
    instructions: 497.38 K (improved by 97.89%)
    heap_increase: 0 pages (no change)
    stable_memory_increase: 0 pages (no change)

---------------------------------------------------
```

Once we release a version containing #190, we can close this issue. Thanks @dragoljub-duric for taking care of this!
